backend:
  name: netlify-api
  url: http://localhost:8080

production:
  backend:
    name: github-api
    repo: ayenzky/starter-template # Path to your Github repository
    branch: develop # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go
public_folder: "assets"

collections: # A list of collections the CMS should be able to edit
  # - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
  #   label: "Post"  # Used in the UI, ie.: "New Post"
  #   folder: "posts" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   fields: # The fields each document in this collection have
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Banner", name: "banner", widget: "image", class: "image featured"}
  #     - {label: "Short Description", name: "shortdesc", widget: "string"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  #   meta: # Meta data fields. Just like fields, but without any preview element
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Categories", name: "categories", widget: "string"}
  - name: "sitedata"
    label: "Site Information"
    files:
      - name: "sitedata"
        label: "Site Information"
        file: "data/site.json"
        description: "edit site information"
        fields:
          - label: "Site Information"
            name: "sitedata"
            widget: "list"
            fields:
              - {label: "Favicon", name: "icon", widget: "image", media_folder: "assets/img"}
              - {label: "Site Logo", name: "logo", widget: "image", media_folder: "assets/img"}
              - {label: "Site name", name: "sitename", widget: "string"}
              - {label: "Website Description", name: "metadesc", widget: "string"}
              - {label: "Author", name: "metauthor", widget: "string"}
              - {label: "Keywords", name: "metakeyword", widget: "string"}
              - {label: "Footer", name: "footer", widget: "markdown"}
              - {label: "Google Analytics", name: "analytics", widget: "markdown"}
  - name: "menus"
    label: "Menu"
    files:
      - name: "result"
        label: "Menu"
        file: "data/menu.json"
        description: "edit/add menu items"
        fields:
          - label: "Menu Item"
            name: "result"
            widget: "list"
            fields:
              - {label: "Item", name: "item", widget: "string"}
              - {label: "Url ex.(/page/slug)", name: "url", widget: "string"}
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Page"  # Used in the UI, ie.: "New Post"
    folder: "page" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    # meta: # Meta data fields. Just like fields, but without any preview element
    #   - {label: "Publish Date", name: "date", widget: "datetime"}
    #   - {label: "Categories", name: "categories", widget: "string"}